= Spring Cloud Deployer for Cloud Foundry image:https://build.spring.io/plugins/servlet/buildStatusImage/SCD-DCF[Build Status, link=https://build.spring.io/browse/SCD-DCF] image:https://badge.waffle.io/spring-cloud/spring-cloud-deployer-cloudfoundry.svg?label=ready&title=Ready[Stories Ready, link=http://waffle.io/spring-cloud/spring-cloud-deployer-cloudfoundry] image:https://badge.waffle.io/spring-cloud/spring-cloud-deployer-cloudfoundry.svg?label=In%20Progress&title=In%20Progress[Stories In Progress, link=http://waffle.io/spring-cloud/spring-cloud-deployer-cloudfoundry]

This project provides a common means to deploy applications to Cloud Foundry based on the Spring Cloud Deployer SPI.

== Building

Clone the repo and type

----
$ ./mvnw clean install
----

The project includes a set of integration tests that can be run against a Cloud Foundry installation, provided that
connection information is correctly set. If credentials are not set correctly, those tests will be silently skipped.
Below is a short list of common Spring Boot @ConfigurationProperties (in environment variable format) that you will need to set in order to deploy applications to Cloud Foundry:

----
# url of the CF API (used when using cf login -a for example)
SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_URL

# name of the space into which modules will be deployed
SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SPACE

# name of the organization that owns the space above
SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_ORG

# the root domain to use when mapping routes
SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_DOMAIN

# Comma separated set of service instance names to bind to the deployed app
SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SERVICES

# username and password of the user to use to create apps
SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_USERNAME
SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_PASSWORD

# whether to allow self-signed certificates during SSL validation
SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SKIP_SSL_VALIDATION
----

Refer to https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/blob/master/src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeployerProperties.java[CloudFoundryDeployerProperties] for a complete listing.

== Services, Disk and Memory settings.

The deployer also supports setting the properties `spring-cloud-deployer-cloudfoundry-services`,
`spring-cloud-deployer-cloudfoundry-memory`, and `spring-cloud-deployer-cloudfoundry-disk` as part of an individual
deployment request.

== Deployed application name settings

To help avoid clashes with routes across spaces on Cloud Foundry, a naming strategy to provide a random prefix to a deployed application is available and is enabled by default.  There are two configuration properties, `enableRandomAppNamePrefix` and `appNamePrefix.  The `appNamePrefix` property defaults to `spring.application.name` if present, otherwise defaults to an empty string.

There are four possible combinations for the name of an application called `time` based on these two property settings.  These are shown in the table below given an application where the name of the deployed application as defined via the deployer's high level API is 'time'

.Application Name
|===
|appNamePrefix | enableRandomAppNamePrefix | application name

|server
|true
|server-unfarming-restabilization-time

|<empty string>
|true
|unfarming-restabilization-time

|server
|false
|server-time

|<emtpy string>
|false
|time






